apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret 
  namespace: ecp-prod
type: Opaque
stringData:
  JWT_SECRET: "PyMK2JEBuRWxzcUJ28kxNYHyR0IQqUvlR7Ol8RTztK54VTjZJNYmcWqjLQryXdJGPaGzHvn1kVI+siZhT6sTWQ=="

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
