apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: ecp-prod

data:
  config.yml: |
    tunnel: a58d41f-3f85-4fa5-a32e-a04c53a7a0e3
    credentials-file: /etc/cloudflared/credentials.json

    ingress:
      - hostname: ecpws-uat.notcode.uk
        service: http://api-gateway:80

      - service: http_status:404