#!/bin/bash
# ─────────────────────────────────────────────────────────────────────────────
# dev-env.sh
#
# Auto-generates .env from your live minikube cluster.
# Resolves the K8s API server port automatically — no manual copy-paste.
#
# Usage:
#   chmod +x dev-env.sh
#   ./dev-env.sh          # generates .env
#   docker compose up     # reads .env automatically
#
# Re-run after every minikube restart (port changes each time).
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

echo "Resolving minikube API server..."

# Get the control plane URL from kubectl
CONTROL_PLANE=$(kubectl cluster-info 2>/dev/null | grep "control plane" | grep -oE 'https?://[^ ]+')

if [ -z "$CONTROL_PLANE" ]; then
  echo "ERROR: Could not get minikube control plane URL."
  echo "       Make sure minikube is running: minikube status"
  exit 1
fi

# Replace 127.0.0.1 with host.minikube.internal so Docker can reach it
K8S_API_SERVER="${CONTROL_PLANE/127.0.0.1/host.minikube.internal}"

cat > .env << ENVFILE
# Auto-generated by dev-env.sh — do not edit manually
# Re-run ./dev-env.sh after every minikube restart

K8S_API_SERVER=${K8S_API_SERVER}
USER=${USER}
HOME=${HOME}
ENVFILE

echo ""
echo "✓ .env generated:"
cat .env
echo ""
echo "Run:  docker compose up --build"