GET http://localhost:5028/api/analyst/status
Accept: application/json

###
GET http://localhost:5028/health/live
Accept: application/json


### api-gateway.local  127.0.0.1 
GET http://127.0.0.1/health/live
Accept: application/json

### 127.0.0.1  
GET http://localhost:5028/api/epc-warehouse
Accept: application/json

### get 
GET http://api-gateway.ecp-dev.svc.cluster.local/health/live
Accept: application/json

### get 
GET http://api-gateway.ecp-dev.svc.cluster.local/api/ecp-warehouse
Accept: application/json

### get 
GET http://api-gateway.ecp-dev.svc.cluster.local/api/order-analyser/health/live
Accept: application/json

### http://api-gateway.ecp-dev.svc.cluster.local/api/order/
GET http://api-gateway.ecp-dev.svc.cluster.local/api/order
Accept: application/json